
name: Caching with npm
on: 
workflow_dispatch:
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
      go: [ '1.14', '1.13' ]
      steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go run hello.go
      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Test
        run: npm test
        
      - run: /install.sh
      - name: Connect Tailscale
        uses: tailscale/github-action@v1
          with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
             - name: check for hello.ipn.dev in netmap
               run:
               tailscale status | grep -q hello
